Invalid:
- all:
  - changed-files:
    - any-glob-to-any-file: 'projects/**'
    - all-globs-to-any-file: 'projects/**'

# Add 'Submission' label to any changes within '/projects' folder or any subfolders
Submission:
- changed-files:
  - any-glob-to-any-file: 'projects/**'

Dev:
- all:
  - changed-files:
    - any-globs-to-any-file: '!projects/**'
