Submission:
- changed-files:
  - any-glob-to-any-file: 'projects/**'

Dev:
  - changed-files:
    - any-glob-to-any-file: '!projects/**'
  

# Invalid:
# - all:
#   - changed-files:
#     - any-glob-to-any-file: '*'
#     - all-globs-to-any-file: 'projects/**'

# # Add 'Submission' label to any changes within '/projects' folder or any subfolders
# Submission:
# - changed-files:
#   - any-glob-to-any-file: 'projects/**'

# Dev:
# - all:
#   - changed-files:
#     - any-glob-to-any-file: '*'
#     - all-globs-to-any-file: '!projects/**'