Javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/javascript/**/*.js", "/javascript/**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/typescript/**/*.ts", "/typescript/**/*.tsx"]

        # - python: ["**/*.py"]
        # - terraform: ["**/*.tf"]
        # - shell: ["**/*.sh"]
        # - api: ["api/**/*"]
        # - frontend: ["frontend/**/*"]
        # - analytics: ["analytics/**/*"]
        # - ci/cd: [".github/workflows/**/*", "bin/**/*", "**/*/Makefile"]
        # - documentation: ["documentation/**/*", "**/*.md"]
        # - infra: ["infra/**/*"]
        # - database: ["api/src/db/**/*"]
        # - openapi: ["api/openapi.generated.yaml"]
        # - storybook: ["frontend/stories/**/*", "frontend/.storybook/**/*"]
