Javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.js", "**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.ts", "**/*.tsx"]
Python:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.py"]

        # - python: ["**/*.py"]
        # - terraform: ["**/*.tf"]
        # - shell: ["**/*.sh"]
        # - api: ["api/**/*"]
        # - frontend: ["frontend/**/*"]
        # - analytics: ["analytics/**/*"]
        # - ci/cd: [".github/workflows/**/*", "bin/**/*", "**/*/Makefile"]
        # - documentation: ["documentation/**/*", "**/*.md"]
        # - infra: ["infra/**/*"]
        # - database: ["api/src/db/**/*"]
        # - openapi: ["api/openapi.generated.yaml"]
        # - storybook: ["frontend/stories/**/*", "frontend/.storybook/**/*"]
