Javascript:
- any:
    - any-glob-to-any-file: ["**/*.js", "**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.ts", "**/*.tsx"]
  - head-branch: "^(a|A).*"
Python:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.py"]

