Documentation:
      - changed-files:
        - any-glob-to-any-file: ['docs/*']
        - head-branch: '/^(?i)(a).*/'
JavaScript:
  - any: 
      - changed-files:
        - any-glob-to-any-file: ['javascript/*']
