Javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/javascriprt/**/*.js", "/javascriprt/**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.ts", "**/*.tsx"]
Python:
- any:
  - changed-files:
    - any-glob-to-any-file: ["**/*.py"]

