Javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/javascriprt/**/*.js", "/javascriprt/**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/typescriprt/**/*.ts", "/typescriprt/**/*.tsx"]
