Javascript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/javascript/**/*.js", "/javascript/**/*.jsx"]
Typescript:
- any:
  - changed-files:
    - any-glob-to-any-file: ["/typescript/**/*.ts", "/typescript/**/*.tsx"]

