name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

jobs:
  label:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Uploads repository content to the runner
        with:
          sparse-checkout: |
            .github
      - uses: actions/labeler@dependabot/npm_and_yarn/types/jest-29.5.14



